image:
  name: ritse/swen344db:latest

services:
  - postgres:11

variables:
  POSTGRES_DB: swen344DB
  POSTGRES_USER: swen344CIUser
  POSTGRES_PASSWORD: bubbles9874

before_script:
  - pip install -r requirements.txt
  - cp exam-2/config/gitlab-credentials.yml exam-2/config/db.yml
  - python --version
  - python exam-2/src/server.py & # fire up the server before we run our tests
  - sleep 3

testrunner:
  script:
    - cd exam-2
    - python -m unittest # run the unit tests
    # - pytest # optional, use instead of unittest. friendlier output.
    # - curl http://localhost:5000 # you can also debug a failure with curl
  stage: test